[project]
name = "test_project"
version = "1.0.0"
description = "Test project for cmake-utils"
authors = ["Test Author <test@example.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = ">=3.8"

[pypi-dependencies]
nanobind = "*"

[tasks]
configure = { cmd = "cmake -S . -B build" }
build = { cmd = "cmake --build build" , depends-on = ["configure"] }